# Generated by Django 3.0.4 on 2021-06-29 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20210629_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ISBN',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='abstract',
            field=models.TextField(default='This is the abstract'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='writer', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.CharField(default='xyz', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('Management', 'Management'), ('Literature', 'Literature'), ('Arts', 'Arts'), ('School', 'School Level'), ('Religion', 'Religion'), ('Law', 'Law'), ('Entrance', 'Entrance Preparation'), ('Government', 'Government Jobs'), ('Miscellenous', 'Miscelleneous')], default='Miscellenous', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('ratings', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(5))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=100)),
                ('interest', models.CharField(choices=[('Fiction', 'Fiction'), ('Engineering', 'Engineering'), ('Science', 'Science'), ('Management', 'Management'), ('Literature', 'Literature'), ('Arts', 'Arts'), ('School', 'School Level'), ('Religion', 'Religion'), ('Law', 'Law'), ('Entrance', 'Entrance Preparation'), ('Government', 'Government Jobs'), ('Miscellenous', 'Miscelleneous')], default='Miscellenous', max_length=100)),
                ('profile_image', models.ImageField(upload_to='media')),
                ('user_type', models.CharField(choices=[('Individual Seller', 'Individual Seller'), ('Wholeseller', 'Wholeseller'), ('Other', 'Other')], default='Individual Seller', max_length=100)),
                ('rating', models.CharField(max_length=50)),
                ('pradesh', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('palika', models.CharField(max_length=50)),
                ('ward_no', models.IntegerField()),
                ('local_add', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
